GET http://localhost:3000 HTTP/1.1

### register valid user
POST http://localhost:3000/register HTTP/1.1
content-type: application/json

{
  "name": "Erwin",
  "email": "test@test.com",
  "password": "Aa45$6aa"
}

### Login valid user
POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
  "email": "test@test.com",
  "password": "Aa45$6aa"
}

### Login invalid user
POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
  "email": "test@test.com",
  "password": "Aa45$6ab"
}
