GET http://localhost:3000 HTTP/1.1

### Signup valid user
POST http://localhost:3000/signup HTTP/1.1
content-type: application/json

{
  "name": "Erwin",
  "email": "test@test.com",
  "password": "Aa45$6aa"
}

### Signin valid user
POST http://localhost:3000/signin HTTP/1.1
content-type: application/json

{
  "email": "test@test.com",
  "password": "Aa45$6aa"
}

### Signin invalid user
POST http://localhost:3000/signin HTTP/1.1
content-type: application/json

{
  "email": "test@test.com",
  "password": "Aa45$6ab"
}

### Verify user if cookie set
POST http://localhost:3000/verify HTTP/1.1
content-type: application/json

{}

### Verify user with bad cookie
# @no-cookie-jar
POST http://localhost:3000/verify HTTP/1.1
content-type: application/json
Cookie: token=badCookie

{}
